In [17]:
import pandas as pd
import numpy as np
import random
import os
import lightgbm as lgb

import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

import sys
sys.path.append("..")
from utils import *
from preprocessing_utils import *
import warnings
warnings.filterwarnings("ignore")

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)

seed_everything(42)

In [18]:
big_6 = ['Man City', 'Arsenal', 'Liverpool', 'Aston Villa', 'Tottenham', 'Man United']
train, valid = load_train_valid()
train['big_6'] = train['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)
valid['big_6'] = valid['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)

valid.reset_index(drop= True, inplace= True)

hometeam_list = list(train['homeTeam'].unique())
dic = team_encoding(train)

lec = LabelEncoder()
lec.fit(train['result'])

result_array = np.zeros((len(valid), 3))
multi_logloss_sum = 0
is_big6 = [0, 1]

for idx in is_big6:
    team_train = train[train['big_6'] == idx]
    team_valid = valid[valid['big_6'] == idx]
    valid_idx = team_valid.index.values
    train_x, train_y, valid_x, valid_y  = preprocessing(team_train, team_valid, dic, is_test=False)
    train_y = lec.transform(train_y)
    valid_y = lec.transform(valid_y)

    if len(valid_x) != 0:
        model = LogisticRegression(max_iter=100, penalty='l2', C=1.0)
        train_x.drop(columns='big_6', inplace=True)
        valid_x.drop(columns='big_6', inplace=True)
        model.fit(train_x, train_y) 
        prediction = model.predict_proba(valid_x)
        result_array[valid_idx] = prediction

    else:
        continue

100%|██████████| 47/47 [00:00<00:00, 875.06it/s]


In [19]:
multi_loloss = log_loss(valid['result'], result_array)
multi_loloss

0.9390064475032408

In [20]:
big_6 = ['Man City', 'Arsenal', 'Liverpool', 'Aston Villa', 'Tottenham', 'Man United']
train, test = load_train_test()
train['big_6'] = train['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)
test['big_6'] = test['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)
test.reset_index(drop= True, inplace= True)

hometeam_list = list(train['homeTeam'].unique())
dic = team_encoding(train)

lec = LabelEncoder()
lec.fit(train['result'])

result_array = np.zeros((len(test), 3))
multi_logloss_sum = 0
is_big6 = [0, 1]

for idx in is_big6:
    team_train = train[train['big_6'] == idx]
    team_test = test[test['big_6'] == idx]
    test_idx = team_test.index.values
    train_x, train_y, test_x= preprocessing(team_train, team_test, dic, is_test=True)
    train_y = lec.transform(train_y)

    if len(test) != 0:
        model = LogisticRegression(max_iter=100, penalty='l2', C=1.0)
        model.fit(train_x, train_y) 
        prediction = model.predict_proba(test_x)
        result_array[test_idx] = prediction

    else:
        continue

sample_submission = pd.read_csv('/home/workspace/DACON/soccer/Data/sample_submission.csv')
sample_submission.iloc[:,1:] = result_array
sample_submission.to_csv('final.csv', index= False)

100%|██████████| 47/47 [00:00<00:00, 753.14it/s]


In [16]:
제출본

NameError: name '제출본' is not defined

In [62]:
a# 너무  잘게 쪼개니깐 성능이 부서짐
big_6 = ['Man City', 'Arsenal', 'Liverpool', 'Aston Villa', 'Tottenham', 'Man United']
train, valid = load_train_valid()
train['big_6'] = train['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)
valid['big_6'] = valid['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)

valid.reset_index(drop= True, inplace= True)

hometeam_list = list(train['homeTeam'].unique())
dic = team_encoding(train)

lec = LabelEncoder()
lec.fit(train['result'])

result_array = np.zeros((len(valid), 3))
multi_logloss_sum = 0
is_big6 = [0, 1]

for idx in is_big6:
    team_train = train[train['big_6'] == idx]
    team_valid = valid[valid['big_6'] == idx]
    valid_idx = team_valid.index.values
    train_x, train_y, valid_x, valid_y  = preprocessing(team_train, team_valid, dic, is_test=False)
    train_y = lec.transform(train_y)
    valid_y = lec.transform(valid_y)

    if len(valid_x) != 0:
        lgbm = lgb.LGBMClassifier()
        lgbm.fit(train_x, train_y, eval_metric='logloss')
        prediction = model.predict_proba(valid_x)
        result_array[valid_idx] = prediction

    else:
        continue

100%|██████████| 47/47 [00:00<00:00, 736.37it/s]


In [63]:
multi_loloss = log_loss(valid['result'], result_array)
multi_loloss

1.165661844744739

In [10]:
# 너무  잘게 쪼개니깐 성능이 부서짐
big_6 = ['Man City', 'Arsenal', 'Liverpool', 'Aston Villa', 'Tottenham', 'Man United']
train, test = load_train_test()
train['big_6'] = train['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)
test['big_6'] = test['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)
test.reset_index(drop= True, inplace= True)

hometeam_list = list(train['homeTeam'].unique())
dic = team_encoding(train)

lec = LabelEncoder()
lec.fit(train['result'])

result_array = np.zeros((len(test), 3))
multi_logloss_sum = 0
is_big6 = [0, 1]

for idx in is_big6:
    team_train = train[train['big_6'] == idx]
    team_test = test[test['big_6'] == idx]
    test_idx = team_test.index.values
    train_x, train_y, test_x= preprocessing(team_train, team_test, dic, is_test=True)
    train_y = lec.transform(train_y)

    if len(test) != 0:
        model = LogisticRegression(max_iter=100, penalty='l2', C=1.0)
        model.fit(train_x, train_y) 
        prediction = model.predict_proba(test_x)
        result_array[test_idx] = prediction

    else:
        continue

sample_submission = pd.read_csv('/home/workspace/DACON/soccer/Data/sample_submission.csv')
sample_submission.iloc[:,1:] = result_array
sample_submission.to_csv('sample_submission_Category_bit_6.csv', index= False)

       matchID  season        date          homeTeam          awayTeam  big_6
0   MATCH_9008  202324  2024-03-09        Man United           Everton      1
1   MATCH_9009  202324  2024-03-09       Bournemouth  Sheffield United      0
2   MATCH_9010  202324  2024-03-09    Crystal Palace             Luton      0
3   MATCH_9011  202324  2024-03-09            Wolves            Fulham      0
4   MATCH_9012  202324  2024-03-09           Arsenal         Brentford      1
..         ...     ...         ...               ...               ...    ...
83  MATCH_9091  202324  2024-05-04  Sheffield United     Nott'm Forest      0
84  MATCH_9092  202324  2024-05-04             Luton           Everton      0
85  MATCH_9093  202324  2024-05-04           Burnley         Newcastle      0
86  MATCH_9094  202324  2024-05-04         Brentford            Fulham      0
87  MATCH_9095  202324  2024-05-04         Liverpool         Tottenham      1

[88 rows x 6 columns]


100%|██████████| 47/47 [00:00<00:00, 875.56it/s]


In [11]:
result_array

array([[0.20056047, 0.21977973, 0.57965979],
       [0.15766662, 0.25114584, 0.59118754],
       [0.09846571, 0.21537607, 0.68615822],
       [0.36785697, 0.29155415, 0.34058888],
       [0.04022417, 0.08098547, 0.87879036],
       [0.29691604, 0.29460951, 0.40847445],
       [0.08930581, 0.20818229, 0.7025119 ],
       [0.17248469, 0.24755462, 0.57996069],
       [0.2421341 , 0.26985507, 0.48801083],
       [0.2408741 , 0.25448574, 0.50464016],
       [0.13536916, 0.25051461, 0.61411623],
       [0.14065375, 0.22985831, 0.62948794],
       [0.26575888, 0.31043897, 0.42380215],
       [0.34067963, 0.27218919, 0.38713118],
       [0.34357291, 0.27936297, 0.37706413],
       [0.31770942, 0.27713361, 0.40515696],
       [0.43545551, 0.28074974, 0.28379475],
       [0.11656762, 0.20893468, 0.6744977 ],
       [0.41555643, 0.30849405, 0.27594952],
       [0.47032369, 0.28769488, 0.24198143],
       [0.0327996 , 0.05020307, 0.91699733],
       [0.1599178 , 0.22401034, 0.61607186],
       [0.

In [58]:
train, valid = load_train_valid()

homeTeam = list(train['homeTeam'].unique())
awayTeam = list(train['awayTeam'].unique())
homeWindic = {}
awayWindic = {}
totalWindic = {}
for team in homeTeam:
    homeWindic[team] = 0
    awayWindic[team] = 0
    totalWindic[team] = 0

home_idx = train[train['result'] == 'H'].index
away_idx = train[train['result'] == 'A'].index

for idx in home_idx:
    team = train.loc[idx]['homeTeam']
    homeWindic[team] = homeWindic[team]+1

for idx in away_idx:
    team = train.loc[idx]['awayTeam']
    awayWindic[team] = awayWindic[team]+1

for team, value in homeWindic.items():
    totalWindic[team] = homeWindic[team] + awayWindic[team]

sorted_team = sorted(totalWindic.items(), key=lambda item: item[1])

range_400_500 = []
range_180_400 = []
range_100_180 =[]
range_50_100 =[]
others =[]
for series in sorted_team:
    n = series[1]
    if n > 400:
        range_400_500.append(series[0])
    elif n>180 and n<400 :
        range_180_400.append(series[0])
    elif n>100 and n<180:
        range_100_180.append(series[0])
    elif n>50 and n<100:
        range_50_100.append(series[0])
    else:
        others.append(series[0])

def team_category(team):
    if team in range_400_500:
        return 0
    elif team in range_180_400:
        return 1
    elif team in range_100_180:
        return 2
    elif team in range_50_100:
        return 3
    elif team in others:
        return 4

In [82]:
params_lgb = {'reg_alpha': 2.1245096608103405e-05, 'reg_lambda': 0.0018526142807772773, 'max_depth': 20, 'num_leaves': 214, 'colsample_bytree': 0.5274034664069657, 'subsample': 0.42727747704497043, 'subsample_freq': 2, 'min_child_samples': 34, 'max_bin': 357}

In [90]:
train, valid = load_train_valid()
train['teamCategory'] = train['homeTeam'].apply(team_category)
valid['teamCategory'] = valid['homeTeam'].apply(team_category)
valid.reset_index(drop= True, inplace= True)

hometeam_list = list(train['homeTeam'].unique())
dic = team_encoding(train)

lec = LabelEncoder()
lec.fit(train['result'])

result_array = np.zeros((len(valid), 3))
multi_logloss_sum = 0
teamCategory = [0, 1, 2, 3, 4]

for idx in teamCategory:
    team_train = train[train['teamCategory'] == idx]
    print(len(team_train))
    team_valid = valid[valid['teamCategory'] == idx]
    valid_idx = team_valid.index.values
    train_x, train_y, valid_x, valid_y = preprocessing(team_train, team_valid, dic, is_test=False)
    train_y = lec.transform(train_y)
    valid_y = lec.transform(valid_y)

    if len(valid_x) != 0:
        lgbm = lgb.LGBMClassifier(**params_lgb)

        # model = LogisticRegression(max_iter=70, penalty='l2', C=1.0)
        train_x.drop(columns='teamCategory', inplace=True)
        valid_x.drop(columns='teamCategory', inplace=True)
        
        lgbm.fit(train_x, train_y, eval_metric='logloss')
        prediction_lgbm = lgbm.predict_proba(valid_x)
        
        # model.fit(train_x, train_y) 
        # prediction = model.predict_proba(valid_x)
        
        result_array[valid_idx] = prediction_lgbm
        # result_array[valid_idx] = prediction
    else:
        continue

2656


100%|██████████| 47/47 [00:00<00:00, 872.04it/s]


2250


100%|██████████| 47/47 [00:00<00:00, 749.97it/s]


1747


100%|██████████| 46/46 [00:00<00:00, 751.38it/s]


1661


100%|██████████| 47/47 [00:00<00:00, 749.04it/s]


606


100%|██████████| 45/45 [00:00<00:00, 749.92it/s]


In [87]:
result_array

array([[0.10083285, 0.22839522, 0.67077193],
       [0.56257691, 0.22914973, 0.20827336],
       [0.15920953, 0.20646963, 0.63432085],
       [0.35824053, 0.32459149, 0.31716798],
       [0.08894275, 0.19070814, 0.72034911],
       [0.45344807, 0.2873504 , 0.25920153],
       [0.48447659, 0.25698598, 0.25853743],
       [0.12738475, 0.28322209, 0.58939316],
       [0.53533375, 0.23900209, 0.22566416],
       [0.19830823, 0.26839132, 0.53330046],
       [0.15983922, 0.27803248, 0.5621283 ],
       [0.05890423, 0.08190409, 0.85919168],
       [0.49208634, 0.28388755, 0.22402611],
       [0.68427297, 0.19305001, 0.12267702],
       [0.47582705, 0.28445913, 0.23971381],
       [0.07285152, 0.08125195, 0.84589653],
       [0.14956529, 0.22594513, 0.62448958],
       [0.15089085, 0.1954403 , 0.65366886],
       [0.06879174, 0.25682502, 0.67438324],
       [0.13270828, 0.25022519, 0.61706653],
       [0.42058204, 0.26497139, 0.31444657],
       [0.32990696, 0.28117852, 0.38891452],
       [0.

In [100]:
result_array

array([[2.96698279e-01, 1.84708936e-01, 5.18592785e-01],
       [7.32017878e-01, 1.48595378e-01, 1.19386744e-01],
       [1.34300541e-01, 1.19812454e-01, 7.45887005e-01],
       [1.08919783e-01, 5.90148844e-01, 3.00931373e-01],
       [1.83245524e-01, 4.50600892e-01, 3.66153585e-01],
       [8.51199314e-01, 8.99007046e-02, 5.88999817e-02],
       [9.71278704e-01, 1.68931695e-02, 1.18281270e-02],
       [4.60541934e-03, 4.95228328e-03, 9.90442297e-01],
       [3.36035334e-01, 2.29012215e-01, 4.34952451e-01],
       [8.79913964e-02, 3.25401679e-02, 8.79468436e-01],
       [1.06561883e-01, 8.66321378e-01, 2.71167391e-02],
       [1.17136212e-03, 1.88292047e-01, 8.10536591e-01],
       [1.38066449e-01, 1.21785567e-01, 7.40147984e-01],
       [9.14631906e-01, 6.50560196e-02, 2.03120743e-02],
       [4.84098322e-01, 1.89928218e-01, 3.25973460e-01],
       [5.68664595e-01, 1.73474628e-01, 2.57860776e-01],
       [4.46329323e-04, 1.50554997e-01, 8.48998674e-01],
       [9.15172399e-02, 6.20020

In [85]:
multi_loloss = log_loss(valid['result'], result_array)
multi_loloss

1.4560613332368428

In [ ]:
# 너무  잘게 쪼개니깐 성능이 부서짐
big_6 = ['Man City', 'Arsenal', 'Liverpool', 'Aston Villa', 'Tottenham', 'Man United']
train, test = load_train_test()
train['big_6'] = train['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)
test['big_6'] = test['homeTeam'].apply(lambda x: 1 if x in big_6 else 0)
test.reset_index(drop= True, inplace= True)

hometeam_list = list(train['homeTeam'].unique())
dic = team_encoding(train)

lec = LabelEncoder()
lec.fit(train['result'])

result_array = np.zeros((len(test), 3))
multi_logloss_sum = 0
is_big6 = [0, 1]

for idx in is_big6:
    team_train = train[train['big_6'] == idx]
    team_test = test[test['big_6'] == idx]
    test_idx = team_test.index.values
    train_x, train_y, test_x= preprocessing(team_train, team_test, dic, is_test=True)
    train_y = lec.transform(train_y)

    if len(test) != 0:
        model = LogisticRegression(max_iter=100, penalty='l2', C=1.0)
        model.fit(train_x, train_y) 
        prediction = model.predict_proba(test_x)
        result_array[test_idx] = prediction

    else:
        continue

sample_submission = pd.read_csv('/home/workspace/DACON/soccer/Data/sample_submission.csv')
sample_submission.iloc[:,1:] = result_array
sample_submission.to_csv('sample_submission_Category_bit_6.csv', index= False)

In [77]:
train, test = load_train_test()
train['teamCategory'] = train['homeTeam'].apply(team_category)
test['teamCategory'] = test['homeTeam'].apply(team_category)
test.reset_index(drop= True, inplace= True)

hometeam_list = list(train['homeTeam'].unique())
dic = team_encoding(train)

lec = LabelEncoder()
lec.fit(train['result'])

result_array = np.zeros((len(valid), 3))
multi_logloss_sum = 0
teamCategory = [0, 1, 2, 3, 4]

for idx in teamCategory:
    team_train = train[train['teamCategory'] == idx]
    team_test = test[test['teamCategory'] == idx]
    test_idx = team_test.index.values
    train_x, train_y, test_x= preprocessing(team_train, team_test, dic, is_test=True)
    train_y = lec.transform(train_y)

    if len(test) != 0:
        model = LogisticRegression(max_iter=70, penalty='l2', C=1.0)
        model.fit(train_x, train_y) 
        prediction = model.predict_proba(test_x)
        result_array[test_idx] = prediction

    else:
        continue

sample_submission = pd.read_csv('/home/workspace/DACON/soccer/Data/sample_submission.csv')
sample_submission.iloc[:,1:] = result_array
sample_submission.to_csv('sample_submission_Category_5.csv', index= False)

  0%|          | 0/6 [00:00<?, ?it/s]

100%|██████████| 45/45 [00:00<00:00, 807.39it/s]


In [78]:
result_array

array([[0.19320742, 0.22229554, 0.58449704],
       [0.08807875, 0.34465579, 0.56726546],
       [0.09598117, 0.16719603, 0.7368228 ],
       [0.38512469, 0.25611224, 0.35876307],
       [0.03537852, 0.07817303, 0.88644845],
       [0.40220029, 0.27105495, 0.32674475],
       [0.04612582, 0.30920567, 0.6446685 ],
       [0.18309737, 0.23169008, 0.58521255],
       [0.19647812, 0.27328843, 0.53023345],
       [0.15822512, 0.26057131, 0.58120357],
       [0.05955877, 0.25964915, 0.68079207],
       [0.09310789, 0.3183356 , 0.58855652],
       [0.1555978 , 0.25164176, 0.59276044],
       [0.37797323, 0.27323767, 0.3487891 ],
       [0.35974114, 0.27073427, 0.36952459],
       [0.35141025, 0.27854719, 0.37004257],
       [0.40740786, 0.29957509, 0.29301704],
       [0.06601412, 0.13499584, 0.79899004],
       [0.33578318, 0.28583548, 0.37838134],
       [0.40217108, 0.26890198, 0.32892694],
       [0.04242349, 0.04330664, 0.91426987],
       [0.23158933, 0.26608315, 0.50232753],
       [0.